image:
  repository: cr.yandex/crprlnbqn4o5dpo58hd8/dds_service
  pullPolicy: IfNotPresent
  tag: "v2026-07-20-r21"

replicaCount: 1

config:
  # Kafka
  KAFKA_HOST: "rc1a-p27s7l68dghcf6i0.mdb.yandexcloud.net"
  KAFKA_PORT: "9091"
  KAFKA_CONSUMER_USERNAME: "producer_consumer"
  KAFKA_CONSUMER_PASSWORD: "TOPAZ540"
  KAFKA_CONSUMER_GROUP: "dds-consumer-group"
  KAFKA_SOURCE_TOPIC: "order-service_orders"
  KAFKA_DESTINATION_TOPIC: "stg-service-orders"

  # PostgreSQL
  PG_WAREHOUSE_HOST: "rc1b-4u7d1q84rb05820d.mdb.yandexcloud.net"
  PG_WAREHOUSE_PORT: "6432"
  PG_WAREHOUSE_DBNAME: "sprint9dwh"
  PG_WAREHOUSE_USER: "db_user"
  PG_WAREHOUSE_PASSWORD: "TOPPOTZ90"

  # Redis
  REDIS_HOST: "rc1b-ak8sflhrqvbfrnre.mdb.yandexcloud.net"
  REDIS_PORT: "6380"
  REDIS_PASSWORD: "ZAPOT0s54"

imagePullSecrets:
  - name: yandex-registry

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
