FROM python:3.10

# Обновление компонентов в контейнере.
RUN apt-get update -y

# Копирование всех файлов в контейнер.
COPY . .

# Запуск установки зависимостей.
RUN pip install -r requirements.txt

# Установка сертификата для подключения к ресурсам в Яндекс Облаке.
RUN mkdir -p /crt
RUN wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" --output-document /crt/YandexInternalRootCA.crt
RUN chmod 0600 /crt/YandexInternalRootCA.crt

# Переход в директорию src
WORKDIR /src

# Указать интерпретатор Python для запуска приложения.
ENTRYPOINT ["python"]

# Запустить файл app.py.
CMD ["app.py"]
